[settings]
kubeContext = "minikube"

# metadata -- add as many key/value pairs as you want
[metadata]
org = "someClient"
maintainer = "k8s-admin"

# define your environments and thier k8s namespaces
# syntax: environment_name = "k8s_namespace"
[namespaces]
staging = "staging" 
production = "default"


# define any private/public helm charts repos you would like to get charts from
# syntax: repo_name = "repo_url"
[helmRepos]
stable = "https://kubernetes-charts.storage.googleapis.com"
incubator = "http://storage.googleapis.com/kubernetes-charts-incubator"

# define the desired state of your applications helm charts
# each contains the following:

[apps]

    [apps.jenkins]
    name = "jenkins" # should be unique across all apps
    description = "first Jira deployment"
    env = "staging" # maps to the namespace as defined in environmetns above
    enabled = true # change to false if you want to delete this app release [empty = flase]
    chart = "stable/jenkins" # changing the chart name means delete and recreate this chart
    version = "0.9.0"
    valuesFile = "values.yaml" # from this TOML file
    purge = false # will only be considered when there is a delete operation


    [apps.vault]
    name = "vault" # should be unique across all apps
    description = "second Jira deployment"
    env = "staging" # maps to the namespace as defined in environmetns above
    enabled = true # change to false if you want to delete this app release [empty = flase]
    chart = "incubator/vault" # don't change the chart name, create a new release instead
    version = "0.1.0"
    valuesFile = "values.yaml" # from this TOML file
    purge = false # will only be considered when there is a delete operation
